version: 0.2
name: CI

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


phases:
  install:
    runtime-versions:
      nodejs: 16.x
    commands:
      - echo Installing dependencies...
      - npm install

jobs:

  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    commands:
      - echo Building the application...
      - npm run build
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
  post_build:
    commands:
      - echo Packaging the application...
      - touch cloudformation.yml 
      - touch cloudformation-output.yml
      - aws cloudformation package --template-file cloudformation.yml --output-template-file cloudformation-output.yml --s3-bucket $S3_BUCKET

artifacts:
  files:
    - cloudformation-output.yml