version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14.x
    commands:
      - echo Installing dependencies...
      - npm install

  build:
    commands:
      - echo Building the application...
      - npm run build

  post_build:
    commands:
      - echo Packaging the application...
      - aws cloudformation package --template-file cloudformation.yml --output-template-file cloudformation-output.yml --s3-bucket $S3_BUCKET

artifacts:
  files:
    - cloudformation-output.yml